use_frameworks!

target 'appdeck-ios-iap_Example' do
  pod 'appdeck-ios-iap', :path => '../'

  target 'appdeck-ios-iap_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'IAPHelper'
  pod 'RMStore', '~> 0.7'
  end
end
